### PR TITLE
uploading 10 ques

### PR DESCRIPTION
**Pull request by dkdev1**

### CODE REVIEW

**Comment by rhythmbhiwani** [comment]
Worng answer
n = 4
arr = 1,3,5,6
t = 5
expected output = 2
your output = 3

**Comment by dkdev1** [comment]
Compile and run it

**Comment by rhythmbhiwani** [comment]
Wrong output for test case
n = 5
array = 1,2,3,4,5
t = 6
Expected output: 5
Your Output: No output

**Comment by dkdev1** [comment]
Ok new one is updated
Check it

**Pull request merged**
